name: CD

on:
  workflow_dispatch:
  
env:
  TARGET_FOLDER: Prototype/platformer-4d-api/target/
  
jobs:
  native_build:
    runs-on: ubuntu-latest
    name: Deploy Quarkus Backend

    steps:

      - uses: actions/checkout@v2
      
      - name: install ssh key
        uses: caberger/install-ssh-key@v1.0
        with:
          ssh-private-key:  ${{ secrets.KEY }}
          user: ${{ secrets.SERVER_USER }}
          server: ${{ secrets.SERVER }}
          alias: platformer4d-server
        
      - name: download artifact "platformer4d-runner"
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ci.yaml
          name: platformer4d-runner
          path: ${{ env.TARGET_FOLDER }}
    
      - name: connect to server and upload artifact "platformer4d-runner"
        run: |
          ssh platformer4d-server "rm -rf ~/dist && mkdir -p ~/dist"
          scp -r ${{ env.TARGET_FOLDER }} platformer4d-server:~/dist
          
      - name: run server jar
        run: |
          ssh platformer4d-server "ls -la ~/dist && cd ~/dist/target/"
          ssh platformer4d-server "java -jar *.jar &"
