name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
env:
  TARGET_FOLDER: Prototype/platformer-4d-api/target/

jobs:
  native_build:
    runs-on: ubuntu-latest
    name: Build Quarkus Backend

    steps:
      - name: checking code
        uses: actions/checkout@master
        
      - name: setup Java 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          
      - name: build image for Backend
        run: mvn package -D quarkus.package.type=uber-jar > /dev/null 2>&1
        working-directory: Prototype/platformer-4d-api/
        
      - name: upload "backend-runner.jar" to "target"
        uses: actions/upload-artifact@v3
        with:
          name: backend-runner
          path: ${{ env.TARGET_FOLDER }}/
          
      - name: checking target directory
        run: ls -la
        working-directory: target
