name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
env:
  TARGET_FOLDER: Prototype/platformer-4d-api/target/

jobs:
  native_build:
    runs-on: ubuntu-latest
    name: Build Quarkus Backend

    steps:
      - name: checking code
        uses: actions/checkout@master
        
      - name: setup Java 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          
      - name: build image for Backend
        run: | 
          mvn package -D quarkus.package.type=uber-jar
          pwd 
          cd target
          ls -l
        working-directory: Prototype/platformer-4d-api/
        
      - name: upload "platformer4d-runner.jar" to "target"
        uses: actions/upload-artifact@v3
        with:
          name: platformer4d-runner
          path: ${{ env.TARGET_FOLDER }}/
          
